---
title: "교재 목록"
---

원 게시글(LinkedIn)의 제목과 실제 링크 대상이 다른 항목이 있어 **실제 책 기준**으로 적었다.

| # | 실제 책 | 저자 | 원 게시글 제목 | 출처 |
|---|---|---|---|---|
| 1 | Understanding Machine Learning: From Theory to Algorithms | Shalev-Shwartz, Ben-David | 동일 | [PDF](https://cs.huji.ac.il/~shais/UnderstandingMachineLearning/understanding-machine-learning-theory-algorithms.pdf) |
| 2 | Mathematics for Machine Learning | Deisenroth, Faisal, Ong | Mathematical Foundations of ML | [PDF](https://mml-book.github.io/book/mml-book.pdf) |
| 3 | Mathematical Analysis of Machine Learning Algorithms | Tong Zhang | 동일 | [PDF](https://tongzhang-ml.org/lt-book/lt-book.pdf) |
| 4 | The Principles of Deep Learning Theory | Roberts, Yaida, Hanin | Theoretical Principles of DL | [arXiv 2106.10165](https://arxiv.org/abs/2106.10165) |
| 5 | Machine Learning with Neural Networks | Bernhard Mehlig | Neural Networks and Learning Machines | [arXiv 1901.05639](https://arxiv.org/abs/1901.05639) |
| 6 | Deep Learning on Graphs | Yao Ma, Jiliang Tang | Graph Deep Learning | [PDF](https://yaoma24.github.io/dlg_book/dlg_book.pdf) |
| 7 | Algorithmic Aspects of Machine Learning | Ankur Moitra | ML: A Probabilistic Perspective | [PDF](https://people.csail.mit.edu/moitra/docs/bookexv2.pdf) |
| 8 | Probability: Theory and Examples (5th ed.) | Rick Durrett | 동일 | [PDF](https://sites.math.duke.edu/~rtd/PTE/PTE5_011119.pdf) |
| 9 | Elementary Probability for Applications | Rick Durrett | Fundamentals of Applied Probability | [PDF](https://sites.math.duke.edu/~rtd/EP4A/EP4A_April2021.pdf) |
| 10 | Advanced Data Analysis from an Elementary Point of View | Cosma Shalizi | Advanced Data Analysis | [PDF](https://stat.cmu.edu/~cshalizi/ADAfaEPoV/ADAfaEPoV.pdf) |

참고: 게시글의 Haykin *Neural Networks and Learning Machines*, Murphy *ML: A Probabilistic Perspective*는 공식 무료 PDF가 없다. Murphy의 후속작 *Probabilistic Machine Learning* 1·2권은 [probml.github.io](https://probml.github.io/pml-book/)에서 무료로 공개돼 있다.


교재 PDF는 저장소를 받은 뒤 `./scripts/download.sh`로 내려받는다 (재배포 금지 조건 때문에 저장소에는 PDF를 올리지 않는다).
